# Generated by Django 3.2.12 on 2022-03-14 04:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(db_column='codigo', max_length=1000)),
                ('name', models.CharField(db_column='nombre', max_length=100, unique=True)),
                ('description', models.CharField(db_column='descripcion', max_length=1000, unique=True)),
                ('state', models.BooleanField(db_column='estado', default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion')),
                ('date_update', models.DateTimeField(auto_now=True, db_column='fecha_edicion')),
            ],
            options={
                'verbose_name': 'Marca',
                'db_table': 'inv_marca',
            },
        ),
        migrations.CreateModel(
            name='EModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='nombre', max_length=100, unique=True)),
                ('description', models.CharField(db_column='Descripcion', max_length=1000, unique=True)),
                ('state', models.BooleanField(db_column='estado', default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion')),
                ('date_update', models.DateTimeField(auto_now=True, db_column='fecha_edicion')),
            ],
            options={
                'verbose_name': 'Modelo',
                'db_table': 'inv_modelo',
            },
        ),
        migrations.CreateModel(
            name='Frequency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='nombre', max_length=100, unique=True)),
                ('description', models.CharField(db_column='descripcion', max_length=100, unique=True)),
                ('state', models.BooleanField(db_column='estado', default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion')),
                ('date_update', models.DateTimeField(auto_now=True, db_column='fecha_edicion')),
            ],
            options={
                'verbose_name': 'Frecuencia',
                'db_table': 'inv_frecuencia',
            },
        ),
        migrations.CreateModel(
            name='Generation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='nombre', max_length=255)),
                ('description', models.CharField(db_column='description', max_length=1000)),
                ('state', models.BooleanField(db_column='estado', default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion')),
                ('date_update', models.DateTimeField(auto_now=True, db_column='fecha_edicion')),
            ],
            options={
                'db_table': 'inv_generacion',
            },
        ),
        migrations.CreateModel(
            name='Heading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(db_column='codigo', max_length=9)),
                ('description', models.TextField(db_column='description', max_length=1000)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion')),
            ],
            options={
                'db_table': 'inv_rubro',
            },
        ),
        migrations.CreateModel(
            name='ItemAssignmentHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_equipment', models.TextField(db_column='nombre_equipo', max_length=1000)),
                ('date', models.DateField(db_column='fecha')),
                ('employee', models.ForeignKey(db_column='empleado', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inv_item_asignacion_cabecera',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='nombre', max_length=255)),
                ('description', models.CharField(db_column='description', max_length=1000)),
                ('state', models.BooleanField(db_column='estado', default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion')),
                ('date_update', models.DateTimeField(auto_now=True, db_column='fecha_edicion')),
            ],
            options={
                'db_table': 'inv_ubicacion',
            },
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(db_column='codigo', max_length=6)),
                ('description', models.TextField(db_column='description', max_length=1000)),
                ('version', models.TextField(db_column='version', max_length=100)),
            ],
            options={
                'db_table': 'inv_software',
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='nombre', max_length=100, unique=True)),
                ('description', models.CharField(db_column='descripcion', max_length=100, unique=True)),
                ('state', models.BooleanField(db_column='estado', default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion')),
                ('date_update', models.DateTimeField(auto_now=True, db_column='fecha_edicion')),
            ],
            options={
                'db_table': 'inv_tecnologia',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_column='codigo', max_length=5)),
                ('description', models.CharField(db_column='description', max_length=1000)),
                ('state', models.BooleanField(db_column='estado', default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion')),
                ('date_update', models.DateTimeField(auto_now=True, db_column='fecha_edicion')),
            ],
            options={
                'db_table': 'inv_tipo',
            },
        ),
        migrations.CreateModel(
            name='SoftwareDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.ForeignKey(db_column='id_cab_asignacion', on_delete=django.db.models.deletion.CASCADE, to='inventory.itemassignmentheader')),
                ('software', models.ForeignKey(db_column='id_software', on_delete=django.db.models.deletion.CASCADE, to='inventory.software')),
            ],
            options={
                'db_table': 'inv_soft_asignacion_detalle',
            },
        ),
        migrations.AddField(
            model_name='software',
            name='type',
            field=models.ForeignKey(db_column='id_tipo', on_delete=django.db.models.deletion.CASCADE, to='inventory.type'),
        ),
        migrations.AddField(
            model_name='itemassignmentheader',
            name='location',
            field=models.ForeignKey(db_column='ubicacion', on_delete=django.db.models.deletion.CASCADE, to='inventory.location'),
        ),
        migrations.CreateModel(
            name='ItemAssigmentHardwareDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_inventory', models.TextField(db_column='codigo_inventario', max_length=25)),
                ('num_serial', models.TextField(db_column='numero_serie', max_length=25)),
                ('quantity', models.IntegerField(db_column='cantidad')),
                ('observation', models.TextField(db_column='observacion', max_length=1000)),
                ('brand', models.ForeignKey(db_column='id_marca', on_delete=django.db.models.deletion.CASCADE, to='inventory.brand')),
                ('frequency', models.ForeignKey(db_column='id_frecuencia', on_delete=django.db.models.deletion.CASCADE, to='inventory.frequency')),
                ('generation', models.ForeignKey(db_column='id_generacion', on_delete=django.db.models.deletion.CASCADE, to='inventory.generation')),
                ('head', models.ForeignKey(db_column='id_cabecera_asignacion', on_delete=django.db.models.deletion.CASCADE, to='inventory.itemassignmentheader')),
                ('heading', models.ForeignKey(db_column='id_rubro', on_delete=django.db.models.deletion.CASCADE, to='inventory.heading')),
                ('model', models.ForeignKey(db_column='id_modelo', on_delete=django.db.models.deletion.CASCADE, to='inventory.emodel')),
                ('type', models.ForeignKey(db_column='id_tipo', on_delete=django.db.models.deletion.CASCADE, to='inventory.type')),
            ],
            options={
                'verbose_name': 'inv_item_asignacion_hardware_detalle',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(db_column='description', max_length=1000)),
                ('state', models.BooleanField(db_column='estado', default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion')),
                ('date_update', models.DateTimeField(auto_now=True, db_column='fecha_edicion')),
                ('model', models.ManyToManyField(to='inventory.EModel')),
                ('type', models.ForeignKey(db_column='id_tipo', on_delete=django.db.models.deletion.CASCADE, to='inventory.type')),
            ],
            options={
                'db_table': 'inv_item',
            },
        ),
        migrations.CreateModel(
            name='HeadingDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(db_column='description', max_length=1000)),
                ('heading', models.ForeignKey(db_column='codigo', on_delete=django.db.models.deletion.CASCADE, to='inventory.heading')),
            ],
            options={
                'db_table': 'inv_rubro_detalle',
            },
        ),
        migrations.CreateModel(
            name='HeadingCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(db_column='valor', max_length=1000)),
                ('heading', models.ForeignKey(db_column='codigo', on_delete=django.db.models.deletion.CASCADE, to='inventory.heading')),
            ],
            options={
                'db_table': 'inv_rubro_capacidad',
            },
        ),
        migrations.AddField(
            model_name='heading',
            name='item',
            field=models.ForeignKey(db_column='id_item', on_delete=django.db.models.deletion.CASCADE, to='inventory.item'),
        ),
    ]
