# Generated by Django 3.2.12 on 2022-03-19 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headingcapacity',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='headingcapacity',
            name='date_updated',
        ),
        migrations.RemoveField(
            model_name='headingcapacity',
            name='user_create',
        ),
        migrations.RemoveField(
            model_name='headingcapacity',
            name='user_update',
        ),
        migrations.AlterField(
            model_name='brand',
            name='description',
            field=models.TextField(blank=True, db_column='descripcion', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='frequency',
            name='description',
            field=models.CharField(blank=True, db_column='descripcion', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='generation',
            name='description',
            field=models.CharField(blank=True, db_column='description', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='generation',
            name='name',
            field=models.CharField(db_column='nombre', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='heading',
            name='description',
            field=models.TextField(blank=True, db_column='description', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='heading',
            name='name',
            field=models.TextField(db_column='nombre', default=0, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='headingcapacity',
            name='value',
            field=models.CharField(db_column='valor', max_length=1000, unique=True, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='location',
            name='description',
            field=models.CharField(blank=True, db_column='description', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(db_column='nombre', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='software',
            name='description',
            field=models.TextField(blank=True, db_column='description', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='software',
            name='name',
            field=models.TextField(db_column='nombre', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='tipo',
            name='description',
            field=models.CharField(blank=True, db_column='description', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='tipo',
            name='name',
            field=models.CharField(db_column='nombre', max_length=100, unique=True),
        ),
    ]
