# Generated by Django 3.2.12 on 2022-03-19 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20220319_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequency',
            name='state',
            field=models.BooleanField(db_column='estado', default=True),
        ),
    ]
