# Generated by Django 3.2.12 on 2022-03-20 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_frequency_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generation',
            options={'ordering': ['id']},
        ),
    ]
