# Generated by Django 3.2.12 on 2022-03-13 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='nombre', max_length=100)),
                ('description', models.CharField(db_column='descripcion', max_length=100)),
                ('state', models.BooleanField(db_column='estado', default=True)),
            ],
            options={
                'db_table': 'doc_area',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='nombre', max_length=100)),
                ('description', models.CharField(db_column='descripcion', max_length=100)),
                ('state', models.BooleanField(db_column='estado', default=True)),
            ],
            options={
                'db_table': 'doc_categoria',
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='nombre', max_length=100)),
                ('description', models.CharField(db_column='descripcion', max_length=100)),
                ('state', models.BooleanField(db_column='estado', default=True)),
            ],
            options={
                'db_table': 'doc_tipo_documento',
            },
        ),
        migrations.CreateModel(
            name='LevelAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='nombre', max_length=100)),
                ('description', models.CharField(db_column='descripcion', max_length=100)),
                ('state', models.BooleanField(db_column='estado', default=True)),
            ],
            options={
                'db_table': 'doc_nivel_acceso',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='nombre', max_length=100)),
                ('description', models.CharField(db_column='descripcion', max_length=100)),
                ('electronicSignature', models.BooleanField(db_column='firma_electronica', default=True)),
                ('manualSignature', models.BooleanField(db_column='firma_manual', default=True)),
                ('create_date', models.DateTimeField(auto_now=True, db_column='fecha_creacion')),
                ('pathFile', models.FileField(db_column='ruta_archivo', max_length=10000, upload_to='files/documents')),
                ('state', models.BooleanField(db_column='estado', default=True)),
                ('area', models.ForeignKey(db_column='id_area', on_delete=django.db.models.deletion.CASCADE, to='documents.area')),
                ('category', models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.CASCADE, to='documents.category')),
                ('documentType', models.ForeignKey(db_column='id_documento', on_delete=django.db.models.deletion.CASCADE, to='documents.documenttype')),
                ('level_access', models.ForeignKey(db_column='id_nivel_acceso', on_delete=django.db.models.deletion.CASCADE, to='documents.levelaccess')),
            ],
            options={
                'verbose_name': 'name',
                'db_table': 'doc_documento',
            },
        ),
    ]
