# Generated by Django 3.2.12 on 2022-03-17 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='description',
            field=models.CharField(blank=True, db_column='descripcion', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.CharField(db_column='nombre', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(blank=True, db_column='descripcion', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_column='nombre', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='description',
            field=models.CharField(blank=True, db_column='descripcion', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(db_column='nombre', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='description',
            field=models.CharField(blank=True, db_column='descripcion', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='name',
            field=models.CharField(db_column='nombre', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='levelaccess',
            name='description',
            field=models.CharField(blank=True, db_column='descripcion', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='levelaccess',
            name='name',
            field=models.CharField(db_column='nombre', max_length=100, unique=True),
        ),
    ]
